/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultsPortalRouteImport } from './routes/results-portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubjectsRouteImport } from './routes/_authenticated/subjects'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScratchCardsRouteImport } from './routes/_authenticated/scratch-cards'
import { Route as AuthenticatedScoresRouteImport } from './routes/_authenticated/scores'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedGradingRouteImport } from './routes/_authenticated/grading'
import { Route as AuthenticatedExportsRouteImport } from './routes/_authenticated/exports'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAssignmentsRouteImport } from './routes/_authenticated/assignments'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedStudentStudentIdRouteImport } from './routes/_authenticated/student.$studentId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsPortalRoute = ResultsPortalRouteImport.update({
  id: '/results-portal',
  path: '/results-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubjectsRoute = AuthenticatedSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScratchCardsRoute =
  AuthenticatedScratchCardsRouteImport.update({
    id: '/scratch-cards',
    path: '/scratch-cards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScoresRoute = AuthenticatedScoresRouteImport.update({
  id: '/scores',
  path: '/scores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGradingRoute = AuthenticatedGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExportsRoute = AuthenticatedExportsRouteImport.update({
  id: '/exports',
  path: '/exports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssignmentsRoute =
  AuthenticatedAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentStudentIdRoute =
  AuthenticatedStudentStudentIdRouteImport.update({
    id: '/student/$studentId',
    path: '/student/$studentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/results-portal': typeof ResultsPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/scratch-cards': typeof AuthenticatedScratchCardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/results-portal': typeof ResultsPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/assignments': typeof AuthenticatedAssignmentsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exports': typeof AuthenticatedExportsRoute
  '/grading': typeof AuthenticatedGradingRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/scores': typeof AuthenticatedScoresRoute
  '/scratch-cards': typeof AuthenticatedScratchCardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/subjects': typeof AuthenticatedSubjectsRoute
  '/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/results-portal': typeof ResultsPortalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/assignments': typeof AuthenticatedAssignmentsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exports': typeof AuthenticatedExportsRoute
  '/_authenticated/grading': typeof AuthenticatedGradingRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/scores': typeof AuthenticatedScoresRoute
  '/_authenticated/scratch-cards': typeof AuthenticatedScratchCardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/subjects': typeof AuthenticatedSubjectsRoute
  '/_authenticated/student/$studentId': typeof AuthenticatedStudentStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/results-portal'
    | '/sitemap.xml'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/audit-log'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/exports'
    | '/grading'
    | '/reports'
    | '/results'
    | '/scores'
    | '/scratch-cards'
    | '/settings'
    | '/staff'
    | '/students'
    | '/subjects'
    | '/student/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/results-portal'
    | '/sitemap.xml'
    | '/announcements'
    | '/assignments'
    | '/attendance'
    | '/audit-log'
    | '/calendar'
    | '/classes'
    | '/dashboard'
    | '/exports'
    | '/grading'
    | '/reports'
    | '/results'
    | '/scores'
    | '/scratch-cards'
    | '/settings'
    | '/staff'
    | '/students'
    | '/subjects'
    | '/student/$studentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/results-portal'
    | '/sitemap.xml'
    | '/_authenticated/announcements'
    | '/_authenticated/assignments'
    | '/_authenticated/attendance'
    | '/_authenticated/audit-log'
    | '/_authenticated/calendar'
    | '/_authenticated/classes'
    | '/_authenticated/dashboard'
    | '/_authenticated/exports'
    | '/_authenticated/grading'
    | '/_authenticated/reports'
    | '/_authenticated/results'
    | '/_authenticated/scores'
    | '/_authenticated/scratch-cards'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/students'
    | '/_authenticated/subjects'
    | '/_authenticated/student/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResultsPortalRoute: typeof ResultsPortalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results-portal': {
      id: '/results-portal'
      path: '/results-portal'
      fullPath: '/results-portal'
      preLoaderRoute: typeof ResultsPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subjects': {
      id: '/_authenticated/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scratch-cards': {
      id: '/_authenticated/scratch-cards'
      path: '/scratch-cards'
      fullPath: '/scratch-cards'
      preLoaderRoute: typeof AuthenticatedScratchCardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scores': {
      id: '/_authenticated/scores'
      path: '/scores'
      fullPath: '/scores'
      preLoaderRoute: typeof AuthenticatedScoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grading': {
      id: '/_authenticated/grading'
      path: '/grading'
      fullPath: '/grading'
      preLoaderRoute: typeof AuthenticatedGradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exports': {
      id: '/_authenticated/exports'
      path: '/exports'
      fullPath: '/exports'
      preLoaderRoute: typeof AuthenticatedExportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assignments': {
      id: '/_authenticated/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AuthenticatedAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/$studentId': {
      id: '/_authenticated/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof AuthenticatedStudentStudentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAssignmentsRoute: typeof AuthenticatedAssignmentsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportsRoute: typeof AuthenticatedExportsRoute
  AuthenticatedGradingRoute: typeof AuthenticatedGradingRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedScoresRoute: typeof AuthenticatedScoresRoute
  AuthenticatedScratchCardsRoute: typeof AuthenticatedScratchCardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedSubjectsRoute: typeof AuthenticatedSubjectsRoute
  AuthenticatedStudentStudentIdRoute: typeof AuthenticatedStudentStudentIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAssignmentsRoute: AuthenticatedAssignmentsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportsRoute: AuthenticatedExportsRoute,
  AuthenticatedGradingRoute: AuthenticatedGradingRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedScoresRoute: AuthenticatedScoresRoute,
  AuthenticatedScratchCardsRoute: AuthenticatedScratchCardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedSubjectsRoute: AuthenticatedSubjectsRoute,
  AuthenticatedStudentStudentIdRoute: AuthenticatedStudentStudentIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResultsPortalRoute: ResultsPortalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
